version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - /var/database/mongo:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - mongo-network
    expose:
      - 27017

networks:
  mongo-network:
    name: mongo-network
    driver: bridge
