version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - /var/database/mongo:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mongod.dev.conf:/etc/mongod.conf
      - /opt/docker-apps/mongo/mongod.log:/var/log/mongodb/mongod.log
    env_file:
      - .env
    ports:
      - 27018:27017 #host:container
    networks:
      - mongo-network
    expose:
      - 27018

networks:
  mongo-network:
    name: mongo-network
    driver: bridge
