version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD_ROOT}
    volumes:
      - /data/db:/data/db
      - /data-backup:/database-backup
      - ./mongod.conf:/etc/mongod.conf
      - /etc/ssl/mongodb.pem:/etc/ssl/mongodb.pem
    command: ["--config", "/etc/mongod.conf"]
    env_file:
      - .env
    ports:
      - 27018:27017 #host:container
    networks:
      - mongo-network
    expose:
      - 27017

networks:
  mongo-network:
    name: mongo-network
    driver: bridge
